### ISSUE TITLE
The mypyc bot is broken

### ISSUE THREAD

**Issue by 97littleleaf11** [mypyc/mypyc-benchmark-results#2]
Benchmarks haven't been updated for two weeks. @JukkaL

**Comment by JukkaL** [comment]
Hopefully fixed by mypyc/mypyc-benchmarks#41.

**Comment by JukkaL** [comment]
We now have up-to-date benchmark results (with some decent gains): https://github.com/mypyc/mypyc-benchmark-results/blob/master/reports/summary-main.md

And thanks for bringing this up!
