### ISSUE TITLE
No results from the benchmarks 

### ISSUE THREAD

**Issue by guizhenwei** [mypyc/mypyc-benchmark-results#4]
As title stated.  No benchmarks shown.

**Comment by JukkaL** [comment]
Looks like the reports and result collection broke around the end of November. That's when I added the mypy self check benchmark, so it's likely related. I will look at this.

**Comment by JukkaL** [comment]
The problem was actually an unplanned upgrade from Python 3.8.5 to 3.8.10 on the benchmarks runner machine. I manually updated all the version information in data to 3.8.10 and this seems to have fixed the reports. Please file another issue if there are still problems in the reports.
